#ifndef INC_H_ 
#define INC_H_

#define INC_EASY_LOGGING

#define ELPP_THREAD_SAFE
#define ELPP_FORCE_USE_STD_THREAD
#define ELPP_DISABLE_DEFAULT_CRASH_HANDLING
#define ELPP_NO_LOG_TO_FILE
#define ELPP_NO_DEFAULT_LOG_FILE
#define ELPP_NO_CHECK_MACROS
#define ELPP_NO_DEBUG_MACROS

#endif // INC_H_
